// import pt from "./data/translate-pt.json" assert { type: "json" };
// import en from "./data/translate-en.json" assert { type: "json" };
import "./navigation.js";
// import "./particles.js";
import "./experiences-data.js";
import "./switch-theme.js";
// import "./time-line.js";
import "./contact.js";
import "./projects.js";
import "./cv-download.js";
import "./copy-email.js";
import "./mobile-menu.js";
