import "./navigation.js";
import "./experiences-data.js";
import "./switch-theme.js";
import "./switch-language.js";
import "./contact.js";
import "./projects.js";
import "./cv-download.js";
import "./copy-email.js";
import "./mobile-menu.js";
